spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 비밀번호 입력
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false
    cloud:
        gcp:
            project-id: test  # GCP 프로젝트 ID
            storage:
                bucket: test # GCS 버킷 이름
jwt:
    secret: vI7p9W8zX2yQ5rL0kM3nB6vC9xZ8aS1dF4gH7jK0lP3mN6bV9cC2vX1zL0kM3nB6 # 임시로 쓰는 보안 키
    expiration: 3600000