name: Deploy to GCP

on:
  push:
    branches: [ main, develop, feature/cors-fix , feature/improve-swagger-docs, feature/add-photo-region ]  # 자동 배포

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 34.47.109.94 >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: |
          if [ ! -s ~/.ssh/id_ed25519 ]; then
            echo "❌ SSH KEY FILE IS EMPTY"
            ls -l ~/.ssh/id_ed25519
            exit 1
          else
            echo "✅ SSH KEY FILE EXISTS"
          fi

      - name: Deploy to GCP
        run: |
          scp -i ~/.ssh/id_ed25519 build/libs/yeogidot-0.0.1-SNAPSHOT.jar wjdckd842080@34.47.109.94:~/
          ssh -i ~/.ssh/id_ed25519 wjdckd842080@34.47.109.94 << 'EOF'
            pkill -f yeogidot.jar || true
            mv ~/yeogidot-0.0.1-SNAPSHOT.jar ~/app/yeogidot.jar
            cd ~/app
            nohup java -Dspring.profiles.active=prod -jar yeogidot.jar > app.log 2>&1 &
          EOF
